### ISSUE TITLE
Adjust CodeGenerator to generate XML comments

### ISSUE THREAD

**Issue by nicolaiw** [zigbeenet/ZigbeeNet#38]

**Comment by ndili561** [comment]
pull request has been generated

**Comment by Mr-Markus** [comment]
thanks for your work. I commented on your PR, because there was an misstake in your code:

https://github.com/ndili561/ZigbeeNet/commit/f3463c18bb7448c2c12b59018908ea790bba9f32#commitcomment-32639487
