### ISSUE TITLE
get device information from IKEA LED1732G11

### ISSUE THREAD

**Issue by bmachuletz** [zigbeenet/ZigbeeNet#65]
Hi,
is anyone able to help me to get device Information (model) from that type of bulb?
The "manufacturer id" is already discovered but i cant get more Information.

thx

**Comment by bmachuletz** [comment]
ok got it:)

First
-----
`networkManager.Send(test, new ReadAttributesCommand { Identifiers = new List<ushort> { ZclBasicCluster.ATTR_MODELIDENTIFIER, ZclBasicCluster.ATTR_MANUFACTURERNAME } });`

Second
---------
In an IZigbeeCommandListener set a filter like this:
```
if (command is ZigBeeNet.ZCL.Clusters.General.ReadAttributesResponse)
{
              ((ZigBeeNet.ZCL.Clusters.General.ReadAttributesResponse)command).Records.ForEach(record =>
                {
                    
                    Console.WriteLine(record.AttributeValue);
                });  
}
```

**Comment by Mr-Markus** [comment]
Hi @bmachuletz ,

you also able to retrieve the model name like following:

```cs
ZigBeeNode node = _networkManager.GetNode(4711);
string model = node.Endpoints.FirstOrDefault().Value.GetInputCluster(ZclBasicCluster.CLUSTER_ID)).GetModelIdentifier(60); // caches value for 60 secods
```

You can do this with any cluster and attribute 😉

**Comment by Mr-Markus** [comment]
I will retrieve something like this here:

![image](https://user-images.githubusercontent.com/38456692/61898863-8f516f00-af1a-11e9-8525-491d8befb3cd.png)

**Comment by bmachuletz** [comment]
Hello Markus,sorry for the late response. I am in holiday mode.In this case you will get the string „Tradfri bulb...“.How can I do this with a different attribute, in order to get the string „LED ...“?

    	
    	

    	
    
  




On Thu, Jul 25, 2019 at 8:27 PM +0200, "Markus" <notifications@github.com> wrote:












I will retrieve something like this here:
